name: play-rust-action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
#   CARGO_TERM_COLOR: always

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo something
        run: echo "Hello Rustaceans"
      - name: multipline steps
        run: |
          pwd
          node -v
          npm -v
