name: play-rust-action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
#   CARGO_TERM_COLOR: always

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo something
        run: echo "Hello Rustaceans"
      - name: multipline steps
        run: |
          pwd
          node -v
          npm -v
  run-dependant-commands:
    runs-on: macos-latest
    needs: run-shell-commands
    steps: 
      - name: voew something
        run: sw_vers
  # dependant-job: 
  run-parallel-commands:
    runs-on: windows-latest
    
    steps: 
      - name: win view something
        run: dir
  # dependant-job: 